### ISSUE TITLE
accord-api should only depend on scalatest in test scope?

### ISSUE THREAD

**Issue by cwei-bgl** [wix/accord#108]
Hi, Thanks for the library.

I got conflicts between my scalatest 3.x dependency and scalatest 2.2.6 which accord-api brings in. The conflicts can be easily resolved by exclusion. I just wonder if accord-api should only depend on scalatest in test scope?

Thanks, Cheng

**Comment by holograph** [comment]
I've been wondering about that. I don't really have an opinion on the matter, so yours wins :-) I'll sort it out for next version.

**Comment by holograph** [comment]
Wait, what? I misread your bug report and thought you meant the `accord-scalatest` module. `accord-api` strictly brings in ScalaTest as a test dependency, i.e. that should not propagate to your own project. Maybe you are doing something funny with your build script?

**Comment by rfranco** [comment]
I have the same issue

```

**Comment by holograph** [comment]
Ah yes, this is a duplicate of #97 (which also includes a workaround until the next version is out). This is basically me being stupid...

**Comment by holograph** [comment]
For reference, the workaround is adding an exclusion to the dependency:

```scala
libraryDependencies += "com.wix" %%% "accord-core" % "0.6.1" excludeAll(ExclusionRule(organization = "org.scalatest"))
```
