### ISSUE TITLE
Please provide accord-core 0.5 as scala 2.12 package

### ISSUE THREAD

**Issue by aquamatthias** [wix/accord#110]
The [marathon project](https://github.com/mesosphere/marathon) tries to move to scala 2.12.
We tried to upgrade to accord 0.6.1 which is compiled against scala 2.12 but we face problems with this - see #109 .

It would be great to unblock this by providing a scala 2.12 package for accord-core 0.5 until #109 is resolved.

Thanks in advance!

**Comment by holograph** [comment]
Hi @aquamatthias, as I remember adding 2.12 support was a bit of a pain, and I'm not happy to spend time backporting it to a 2-year-old release. Let's give #109 a couple days first and, if we can't resolve it satisfactorily, I'll give your request another look?

**Comment by aquamatthias** [comment]
@holograph Thanks for the feedback. Happy to move forward with #109. The intent of this ticket was to separate the 2 things (scala 2.12 and using accord 0.6.1). Out of curiosity: what were the problems you run into with scala 2.12?

**Comment by holograph** [comment]
@aquamatthias Is this still needed/desirable given the release of 0.7?

**Comment by aquamatthias** [comment]
The only way is up...  I will close this issue.
