### ISSUE TITLE
wix/accord: Validate Nested Class

### ISSUE THREAD

**Issue by SrijeshKhanal** [wix/accord#113]
<h1> How can I validate nested class? </h1>

<h3> For example I have following case classes: </h3>

    case class PreTest(a: Option[String], b: Option[String], c: Option[String])
    case class TestMini(x: Option[String], y: Option[String], z: Option[String])
    case class Exam(p:Option[String], preTest: Option[PreTest], testmini: Option[TestMini])

<h4> I would like to validate following fields: </h4> 
    p must not be Empty </br>
    preTest. must not be Empty </br> 
    y must not be Empty and </br>
    z must not be Empty
  </br>
    
**<p>I have done validation in following way</p>**

    object ExamValidator{ 
     val validateExam = validator[Exam] { k =>
         k.p must not Empty
         k.preTest.get.b is notEmpty 
         k.testmini.get.y is notEmpty 
         k.testmini.get.z is notEmpty
       }
    }

<p> But This returns <strong>None.get Error</strong> When I tried to validate <I>Empty Json</I> as following </br>
    {
    }

<p>And also I tried in following way: </p>

    object ExamValidator{ 
      val validateExam = validator[Exam] { k =>
          k.preTest match{
               case n if n.isDefined => k.testmini match {
                                                case m if m.isDefined =>  (k.p must not Empty) and
                                                                                          (k.preTest.get.b is notEmpty ) and
                                                                                          (k.testmini.get.y is notEmpty) and 
                                                                                          (k.testmini.get.z is notEmpty)
                                                case None => (k.p must notEmpty) and (k.testmini must notEmpty)
                                              }  
               case None => k.testmini match {
                                  case h if h.isDefined => (k.p must not Empty) and
                                                                         (k.preTest must notEmpty ) and
                                                                         (k.testmini.get.y is notEmpty) and 
                                                                         (k.testmini.get.z is notEmpty)
                                  case None => (k.p must notEmpty) and (k.testmini must notEmpty) and (k.preTest must notEmpty)
                                  }  
       }

<p>This way we can validate for most of the case like:</p><br/>
Case 1: <br/>
{
}

Case 2:
{
 "p":"aaa"
}
  
Case 3:
{
 "p":"aaa",
 "preTest":{}
 }

<h3> But we get Error (None.get Error) when we try to validate as follows: </h3>
    { </br>
       "p":"aaa", </br>
       "testmini":{} </br>
    }

<strong>How can I validate above case i.e.</strong>
    {
      "p":"aaa",
      "testmini":{}
    }

**Comment by holograph** [comment]
Hi @SrijeshKhanal, `Option`s are simply collections and you can use the `.each` operator for this purpose. Furthermore, in this case you should probably split these off into separate validators:

```scala
object ExamValidator{ 
  implicit val validatePretest = validator[Pretest] { p => p.b is notEmpty }
  implicit val validateTestmini = validator[TestMini] { t => t.y is notEmpty; t.z is notEmpty }
  implicit val validateExam = validator[Exam] { k =>
     k.p must not Empty
     k.preTest.each is valid
     k.testmini.each is valid 
   }
}
```

Although this is written down in the [DSL guide](http://wix.github.io/accord/dsl.html) it's obviously not clear enough, if you have any ideas how to make it more visible/prominent I'd appreciate them...

**Comment by SrijeshKhanal** [comment]
@holograph  
<h2>Thanks for the reply </h2> 
 <h4>This does not work for following case:</h4>
    {
        "p": "abc"
    }

<p>In the above case it does not checks whether preTest and testmini is defined or not.</p>

We want validation for following cases:
Case 1: 
    {}

Case 2:
    {
       "p":"abc"
    }

Case 3: 
    {
     "p":"abc",
     "preTest":{}
    }

Case 4: 
     { 
      "p":"aaa", 
      "testmini":{} 
     }

Case 5: 
     { 
      "preTest":{}, 
      "testmini":{} 
     }

<p><strong>The example provided works for all cases except Case 2 i.e.</strong></p>
    {
       "p":"abc"
    }

<h3>We want provided Json to be valid only in following case:</h3>
     { <br/>
      "p":"abc",<br/>
      "preTest":{"b":"xy"}, <br/> 
      "testmini":{"y":"hat", "z":"Don"} <br/>
     }
