### ISSUE TITLE
Does this library play nice with Java?

### ISSUE THREAD

**Issue by hntd187** [wix/accord#118]
While I don't mind using Scala for this, would other people in my group who make use of pure Java be able to use the library without much trouble? I know you guys probably wouldn't need it, but would you have any interest in a shim over accord's types to make at least `Result` better to deal with in Java?

**Comment by holograph** [comment]
I don't see why Accord would not be usable from Java, although that was
never a design goal. Applying validators and processing results should be
trivial as-is, but two things you don't get are implicit resolution (so you
have to manually look up the right instance and call .apply) and the
definition DSL.

I would certainly not object to any useful contribution around Java
support, and would be happy to assist with the effort as best I can.
