### ISSUE TITLE
Publish scala 2.13 version

### ISSUE THREAD

**Issue by rfranco** [wix/accord#145]
There is only version with scala 2.13.0-M5

**Comment by holograph** [comment]
Yeah, it’s pretty much ready for release - I’ve made sure resetallattrs was available ahead of time

**Comment by zchbndcc9** [comment]
Status update on this?

**Comment by noam-almog** [comment]
i will publish a new version today, sorry for the delay

**Comment by zchbndcc9** [comment]
Perfect, and no worries. Thanks for the speedy response

**Comment by don41382** [comment]
Are there any plans for public release on `2.13.0`?

**Comment by noam-almog** [comment]
`0.7.4` supports 2.13 and it was release in Aug
