### ISSUE TITLE
Accord 0.7.5 has explicit dependency on ScalaTest

### ISSUE THREAD

**Issue by timcharper** [wix/accord#151]
Accord 0.7.3 had a test dependency on ScalaTest, but releases 0.7.4 and 0.7.5 fail to mark the dependency as a test dependency

You can see here it is a test dependency:
https://mvnrepository.com/artifact/com.wix/accord-api_2.12/0.7.3

And here, it is an explicit dependency:
https://mvnrepository.com/artifact/com.wix/accord-api_2.12/0.7.4
https://mvnrepository.com/artifact/com.wix/accord-api_2.12/0.7.5

**Comment by noam-almog** [comment]
api module  % "test" was removed accidently during the 2.13 build, i will publish a new version today
thanks 👍

**Comment by noam-almog** [comment]
PR #152

**Comment by noam-almog** [comment]
publishing 0.7.6 today, it will be fixed on that release, thanks for the report

**Comment by timcharper** [comment]
Thank you @noam-almog !
