### ISSUE TITLE
is Accord no longer maintained?

### ISSUE THREAD

**Issue by andyczerwonka** [wix/accord#153]
Given there is a pretty healthy backlog and there have been minimal commits in months, I was wondering if Accord is no longer being maintained outside of external PR's? I also noticed very limited activity on the Gitter channel (it took just over a week to see any activity at all). So, concretely:

Is Accord no longer maintained because:

1. Users find it is full featured and does not need significant investment.
2. User have moved on to another library for this purpose.
3. Validation is easy to roll, so just roll your own.

**Comment by noam-almog** [comment]
For now i would go with option 1, since @holograph did such a great job most of the needed features are already in. i'm keeping the library updated with latest deps and when bugs are reported i usually fix them in a reasonable time.
