### ISSUE TITLE
Max Length?

### ISSUE THREAD

**Issue by lenzenc** [wix/accord#31]
Maybe I missed some documentation but does accord have the ability to check a max or min length of a "string" property?

**Comment by avitaln** [comment]
try:
theString has(size between(min, max))

**Comment by lenzenc** [comment]
Thanks...looks like if you just want to check max length you can do the following;

thString has size <= max

**Comment by lenzenc** [comment]
Another question, is there a way to inline multiple checked in one line, for example;

theString is notEmpty  and has size <= max

**Comment by lenzenc** [comment]
One more question, is there an example for "custom" validations?  Similar to how you can write one for RoR?

**Comment by avitaln** [comment]
you can use combinations of is/and/or and if you have case class inside another case class - for example address inside person - then you write validator for address, and for person you do: "address is valid"

**Comment by lenzenc** [comment]
Thanks @avitaln, how about custom validations, again similar to RoR.  For example I might have custom business logic to check the uniqueness of a combination of two properties?

**Comment by lenzenc** [comment]
Trying out multiple expression on on property, for example;
```
    case class Person(name: String, age: Int)

    implicit val personValidator = validator[Person] { p =>
      p.name is notEmpty and size <= 5
      p.age should be > 0
    }
```
But getting a compile error;

ound   : p.name.type (with underlying type String)
[error]  required: Int with String
[error]  Note: implicit value personValidator is not applicable here because it comes after the application point and it lacks an explicit result type
[error]       p.name is notEmpty and size <= 5

**Comment by karolisbu** [comment]
The workaround could be just (and is added my scala macros):
```
  implicit val personValidator = validator[Person] { p =>
    p.name is notEmpty
    p.name has size <= 5
    p.age should be > 0
  }
```
or 

```
  implicit val personValidator = validator[Person] { p =>
    p.name is notEmpty and (p.name has size <= 5)
    p.age should be > 0
  }
```

**Comment by holograph** [comment]
Your second suggestion is not a workaround, it's actually the implemented syntax, though I'd recommend parenthesizing the first expression as well:

```scala
(p.name is notEmpty) and (p.name has size <= 5)
```

It's rather poorly documented because, well, it appears bootstrapping a proper documentation project with Jackyl or Sphinx is actually a lot more work than you'd think :-/  (If you ever look for a way to contribute, bootstrap a sensible documentation site -- that'd be amazingly helpful!)

**Comment by holograph** [comment]
As for custom validators, that's also pretty poorly documented, but a validator is essentially a `Function1[T, com.wix.accord.Result]`, and there's a bunch of base helpers you can use. Example:

```scala
"Accord" should "let you write custom validators" in {
  import com.wix.accord.ViolationBuilder._
  val happy = 
    new NullSafeValidator[String](
      test    = _ startsWith "happy", 
      failure = _ -> "is not happy" 
    )
      
  val goodString = {
    import com.wix.accord.dsl._
    validator[String] { s => s is happy }
  }
      
  goodString("happy happy joy joy") should succeed
}
```

**Comment by holograph** [comment]
This is now properly documented on the [site](http://wix.github.io/accord/dsl.html).
