### ISSUE TITLE
Add set-style "is one of" combinator

### ISSUE THREAD

**Issue by lenzenc** [wix/accord#32]
How do you write a validation to make sure if a value is within a Seq of values, for eample;

value: String
mySeq Seq("V1",V2",etc)

value must be one of the values in mySeq?

**Comment by karolisbu** [comment]
Hi,
I wrote the custom validator method by extending Accord BaseValidator:
```
  def oneOf[T](col : T*) : Validator[T] = new BaseValidator[T](
    col.contains,
    v => v -> s"'$v' is not one of (${col.mkString(",")})"
  )
```
the usage looks like:
```
case class Person(name: String, title: String) 
 implicit val personValidator = validator[Person] { p =>
    p.name is notEmpty and (p.name has size <= 5)
    p.title is oneOf("Mr", "Mrs", "Miss")
 }
```

**Comment by holograph** [comment]
Seems legit :-)  I don't know that this is "interesting" enough for inclusion in the broader combinator library, but then we don't have any guidelines on that. I'll modify the issue to indicate that it's an enhancement request and leave it open for a while to see if people are interested.
