### ISSUE TITLE
Document available validations

### ISSUE THREAD

**Issue by janekdb** [wix/accord#33]
`accord` has a simple and useful dsl but it required a hunt through the source code to find the available validations in `StringOps` and friends.

Suggestions,

* Summarise available validations in `README` OR
* Link to user document if this already exists somewhere else

**Comment by holograph** [comment]
A definite wishlist item. Some discussion going on on the [Gitter channel](https://gitter.im/wix/accord) if you're interested.

**Comment by holograph** [comment]
Started working on it via branch `gh-pages` (the site is accessible via http://wix.github.io/accord/). I'm still playing around with Jekyll, but once I manage to get sensible markdown support the actual documentation can progress.

**Comment by janekdb** [comment]
Looks good so far!

**Comment by holograph** [comment]
Major milestone achieved, enough that I'm comfortable closing this issue!
Check out the resulting documentation, specifically the pages about the [API](http://wix.github.io/accord/api.html), [DSL](http://wix.github.io/accord/dsl.html) and combinator [library](http://wix.github.io/accord/dsl.html#combinator-library).

Could still use some improvement, and a TOC is definitely high on my wishlist (would already be in place if I weren't such a CSS luddite), but it's finally useful, I hope :-)
