### ISSUE TITLE
Publish and link to API docs

### ISSUE THREAD

**Issue by janekdb** [wix/accord#34]
This project would be better still if the API docs were published somewhere.

I have been through this with one of my projects and settled on a simple process. It's not fully automated but works fine,

* Build Maven site locally including API docs
* Commit to `gh-pages` branch
* Push

The docs are then available from GitHub pages.

**Comment by holograph** [comment]
Largely related to #33, so much so that, given proper documentation of library features, I don't think there's any point for "JavaDoc"-style publishing. Closing as duplicate.
