### ISSUE TITLE
Regression: Boolean combinators can no longer be applied to a single term

### ISSUE THREAD

**Issue by holograph** [wix/accord#37]
As a result of the DSL change in #27, since release 0.4.1 it is no longer valid to apply several rules to a single term in some cases; for example, trying to compile the following validator:

```scala
  case class SingleTermTest( term: String )
  val singleTermValidator = validator[ SingleTermTest ] { st => st.term is notNull and notEmpty }
```

Results in the following compiler error:

```
[error] /Users/tomer/dev/accord/core/src/test/scala/com/wix/accord/tests/dsl/BooleanOpsTests.scala:120: type mismatch;
[error]  found   : <:<[Nothing,Nothing]
[error]  required: T => com.wix.accord.combinators.HasEmpty
[error]     (which expands to)  T => AnyRef{def isEmpty: Boolean}
[error]   val singleTermValidator = validator[ SingleTermTest ] { st => st.term is notNull and notEmpty }
[error]
```

This is because `and` now takes a type parameter `U`, and requires a right-hand combinator of type `Validator[U]`. Since there's nothing to guarantee that the `notEmpty` invocation operates on the same term, the type inferencer doesn't see any constraints on `U` and borks.

Reported by @obruker and @noam-almog.

**Comment by holograph** [comment]
This is evidently a lot less trivial than you'd expect. The problem is that the `and` rule needs to apply in two separate cases:

* The simple case is where the types for both operands are known. For instance, `(st.term is notNull) and (st.term is notEmpty)` is a combination of two known types (`Validator[String]`).
* The type of the left-hand operand is known, but the right-hand side isn't; this is the case for single-term sentences. In the original example the first part (`st.term is notNull`) is known (`Validator[String]`), but the type for `notEmpty` isn't and needs to be inferred. 

For type inferencing to make sense in the second case, the signature for `and` must contain an overload with no type parameters, and it has to be completely unambiguous. Unfortunately, because of erasure it's impossible to declare both specific and generic overloads:

```
scala> trait Validator[-T]
defined trait Validator

scala> implicit class BooleanOps[T](lhs: Validator[T]) {
     |   def and[U](rhs: Validator[U]) = println("heterogeneous")
     |   def and(rhs: Validator[T]) = println("homogeneous")
     | }
<console>:10: error: double definition:
def and[U](rhs: Validator[U]): Unit at line 9 and
def and(rhs: Validator[T]): Unit at line 10
have same type after erasure: (rhs: Validator)Unit
         def and(rhs: Validator[T]) = println("homogeneous")
```

This is further complicated by the fact that the right-hand operand can be generic, as is the case for `notEmpty` (and others). The closest I've managed to come up with:

```scala
// Mock validators:
trait Validator[-T]
def validator[T] = new Validator[T] {}                                         
def nonEmpty[T <% {def isEmpty:Boolean}] = validator[T]

implicit class BooleanOps[T](lhs: Validator[T]) { 
  def and[U](rhs: Validator[U]) = println("heterogeneous")
  // Implicit evidence required so that erased signatures don't conflict:
  def and[U>:T](rhs: Validator[U])(implicit ev: T<:<U) = println("homogeneous") 
}

validator[String] and validator[String]		// Prints "homogeneous"
validator[String] and validator[Int]		// Prints "heterogeneous"
validator[String] and nonEmpty				// Fails to compile!
```

That last line fails because `nonEmpty` is generic, and there's nothing to constrain the type inference. One way to attack this would be to have a very specific `def and(rhs: Validator[T])` overload to support the type inferencer, and a more generic overload for heterogeneous types; unfortunately I know of no way to encode a rule such as "T and U have no subtyping relation" in Scala.

Ideas are more than welcome...

**Comment by holograph** [comment]
Asked a question on [StackOverflow](stackoverflow.com/questions/30191554/how-can-i-prove-that-two-types-have-no-subtyping-relation-in-scala), hopefully someone will be able to help :-)

**Comment by holograph** [comment]
Well it looks like there *is* a way to encode this constraint (see [StackOverflow](http://stackoverflow.com/questions/6909053/enforce-type-difference)), but unfortunately it does not apply this case -- the parameterized `and` is still considered a valid overload, and the type inferencer goes haywire. So there goes that idea.

Until someone comes up with another avenue of research, there are two workarounds you can use:
* For `and`s, split your rule into two separate rules (there's an implicit `and` within any validation block);
* For `or`s, fully-qualify and parenthesize your rules, e.g.:

  ```scala
  p.firstName is aNull or nonEmpty 
  // Becomes...
  (p.firstName is aNull) or (p.firstName is nonEmpty)
  ```

**Comment by nadavwe** [comment]
how about changing the name from "and" to something else?
so you have two names that basically do similar things.
I would probably go with andAlso or && or + (or any two of them... :).
I hope i understood the problem correctly...

**Comment by holograph** [comment]
@nadavwe That's easy and you don't need me for it (see below for a cut+paste solution). I'm reluctant to add a semantically-identical conjunction to the DSL just to work around a language constraint, especially when the available workarounds are so simple.

If you want to add `andAlso` to your own codebase, this will work:
```scala
  import com.wix.accord.Validator
  import com.wix.accord.combinators.And
  implicit class ValidatorExtensions[ T ]( validator: Validator[ T ] ) {
    def andAlso( rhs: Validator[ T ] ): Validator[ T ] = new And( validator, rhs )
  }

  // Usage example:
  case class SingleTermTest( term: String )
  val singleTermValidator = validator[ SingleTermTest ] { st => st.term is notNull andAlso notEmpty }
```
