### ISSUE TITLE
For string, have size == 7 does not compile

### ISSUE THREAD

**Issue by xiaodongw** [wix/accord#39]
I got the following compile error for the code:
o have size == 7

Which o is a string.
[info] Compiling 5 Scala sources to /Users/alfred/code/trading-service/trading-service-server/target/scala-2.10/classes...
[error] /Users/alfred/code/trading-service/trading-service-server/src/main/scala/com/loyal3/trading/validation/Validation.scala:12: type mismatch;
[error]  found   : com.wix.accord.combinators.EqualTo[(Int, String)]
[error]  required: com.wix.accord.Validator[Int]
[error]  Note: implicit value validExecuteBuyTradeRequest is not applicable here because it comes after the application point and it lacks an explicit result type
[error]     o have size == 7  //todo this syntax does not work
[error]                 ^
[error] one error found
[error] (server/compile:compile) Compilation failed

But if I change it to something like:
o have size >= 7
then it compiles.

**Comment by holograph** [comment]
Interesting. I'll have to look into the error a bit further to understand why the error message is so weird; at any rate, the intended syntax (which will hopefully be documented soon along with the rest of #33) is: 
```scala
o should have size == 7
```
This should work around your problem in the meantime.

**Comment by xiaodongw** [comment]
Thanks for the quick response. It still does not work, the code is like this:
val validBetaSecurityNumber = validator[String] { o =>
    o is notEmpty
    o should have size == 7
  }

  val validBetaAccountId = validator[String] { o =>
    o is notEmpty
    o should have size == 8
  }

Then I got the error:
[info] Compiling 7 Scala sources to /Users/alfred/code/trading-service/trading-service-server/target/scala-2.10/classes...
[error] /Users/alfred/code/trading-service/trading-service-server/src/main/scala/com/loyal3/trading/validation/Validation.scala:12: ';' expected but integer literal found.
[error]     o should have size == 7
[error]                           ^
[error] /Users/alfred/code/trading-service/trading-service-server/src/main/scala/com/loyal3/trading/validation/Validation.scala:17: ';' expected but integer literal found.
[error]     o should have size == 8
[error]                           ^
[error] two errors found
[error] (server/compile:compile) Compilation failed
[error] Total time: 2 s, completed Jun 1, 2015 6:43:33 PM

I'm using Scala 2.10.5

**Comment by holograph** [comment]
Strange, I'll have a look as soon as I can. Thanks for the report!

**Comment by holograph** [comment]
I've misled you with my previous comment, i.e. the right syntax is `o has size == 7`. Regardless, I've replicated your issue and am looking into it.
