### ISSUE TITLE
collection.each should not fail on empty collection

### ISSUE THREAD

**Issue by leoconco** [wix/accord#41]
collection.each is notEmpty should not fail if collection is empty
I want to validate the field "tags", my object could not have any tag, but if there are tags, the empty string should not be accepted.
I don't find a way to do it in accord.
```
x.tags.each is notEmpty
```
results in 
```
RuleViolation(null,is a null,Some(tags))
```

**Comment by holograph** [comment]
Your usage is correct, but I haven't been able to replicate your issue. From the violation it's very likely that `x.tags` (i.e. the collection itself) is null. If that's not the case, please post a bit more of the code and reopen the issue...

**Comment by leoconco** [comment]
Indeed x.tags is null , but if I want to validate 
```
x.tags.each is matchRegexFully("\\S+".r)
```
but x.tags could be null, I have no alterative.
I mean, I want to validate: x.tags could be empty, but if it has elements, these elements should not include spaces.
The basic case where x.tags is null should return valid instead of failure.

**Comment by holograph** [comment]
Nulls go against the grain of the Scala language, so I'd prefer not to make this a first-class construct. You can get the behaviour you want with a little boolean algebra:

```scala
import com.wix.accord._
import dsl._

case class Container(tags: Seq[String])
implicit val v = validator[Container] { c =>
  (c.tags is aNull) or (
    (c.tags is notEmpty) and 
    (c.tags.each should matchRegexFully("\\S+".r))
  )
}
```

This gets you what you need:
```
scala> validate(Container(Seq.empty))
res0: com.wix.accord.Result = Failure(Set(GroupViolation(Container(List()),doesn't meet any of the requirements,None,Set(RuleViolation(List(),is not a null,Some(tags)), RuleViolation(List(),must not be empty,Some(tags))))))

scala> validate(Container(null))
res1: com.wix.accord.Result = Success

scala> validate(Container(Seq("  a")))
res2: com.wix.accord.Result = Failure(Set(GroupViolation(Container(List(  a)),doesn't meet any of the requirements,None,Set(RuleViolation(List(  a),is not a null,Some(tags)), RuleViolation(  a,must fully match regular expression '\S+',Some(tags))))))

scala> validate(Container(Seq("a")))
res3: com.wix.accord.Result = Success
```

**Comment by leoconco** [comment]
Thanks, that is what I needed, I tried with if inside the validator before and didn't work, but this does.
Suggestion: cheatsheet
Great library.

**Comment by holograph** [comment]
Thanks for the feedback :-)  You're right that documentation is lacking, I'm working on that (see #33).
