### ISSUE TITLE
Support async operations (Future)

### ISSUE THREAD

**Issue by AmirKarimi** [wix/accord#53]
For example we need to check if some fields are available/valid in database. As our data-access library is async, is there any way to build a custom async validation rule?

**Comment by holograph** [comment]
Since Accord operates on constituted (complete, fully loaded, what-have-you) objects, this will require some care in order not to mix the two concerns. Can you give an example, so we have something to start discussing syntax around?

**Comment by AmirKarimi** [comment]
You're right, we shouldn't mix the two concerns. I'll explain with an example.

We use NoSQL DB (Mongodb). Suppose the following classes:
```scala
case class City(id: BSONObjectID, title: String, provinceId: BSONObjectID)
case class Province(id: BSONObjectID, title: String)
```
Each city has a province. We want to make sure that the `provinceId` of the `City` class is defined in the province collection. Accord should not be aware that I'm going to do a DB validation but it would be very nice if it allowed me to implement a custom async validation class like `CityIdExistsInDB` which gets a `BSONObjectID` and returns a `Future` result indicating whether the city with the corresponding ID exists in DB or not.

**Comment by holograph** [comment]
That has pretty massive ramifications on the base API. For example, would a validation of a `City` return `Result` or `Future[Result]`? Would the combinator library as well as the DSL have to be extended to support e.g. `And(f1, f2, ... fn)` where `f`s are futures? Should it be split down the middle into "blocking" and "nonblocking" variants?

I would argue that validations are designed to be stateless, and certainly not depend on external (certainly over-the-wire) systems.

**Comment by AmirKarimi** [comment]
Yeah, it would be a huge refactoring and the architecture can be inspired by what is done in Play framework actions.

OK. Finally, we would use Accord for stateless validations, but for external validations we probably have to develop our own framework which will be inspired by Accord. If so, it certainly would be published on Github. Please let me know if you have any recommendations.

Thanks
