### ISSUE TITLE
Detecting position in collection combinator

### ISSUE THREAD

**Issue by zunder** [wix/accord#57]
I am having a validator containing collection combinator:
`myList.seq.each is valid`
Now what I need to know is the position of elements, which violate my model. All I get is rather a grouped violation, containing all the violations, but no position in the sequence.
What is best practise to tackle that issue?

**Comment by holograph** [comment]
Position only makes sense in the context of a randomly-accessible sequence, whereas the `.each` modifier is intended to be used on any collection. This seems a bit highly specialized for the library itself, but let's tackle this from another direction for now: What should be the failure derived from this code? (this is not a trick question, I'm contemplating whether or not the result model makes sense)

```scala
case class Container(coll: Seq[Int])

implicit val containerValidator=validator[Container] { c => c.coll.each should be >= 0 }

validate(Container(Seq(1, 2, 3, -4, 5, -6))) == ?
```

**Comment by alexanderweber** [comment]
Good question - I would appreciate to have something like this:

```scala
scala> validate(Container(Seq(1, 2, 3, -4, 5, -6)))
res1: com.wix.accord.Result = 
  Failure(Set(
    RuleViolation(-4,got -4, expected 0 or more,Some(coll[3])),
    RuleViolation(-6,got -6, expected 0 or more,Some(coll[5]))
  ))
```
I am not explicitly against the current functionality of `each`. I just need some collection combinator which provides that functionality.

Maybe some context would explain why I am in need for that information:
I am trying to validate some user input from an API. Therefore I need to give him some feedback on where he might find the violation he made. The example you made is rather small, but if there is an array of say 100 items, I would be glad to guide him to the position of error.

**Comment by holograph** [comment]
I've played around with the codebase a bit; this will require a not-insignificant amount of work on the innards of Accord (how descriptions are generated and propagated). I think this is a worthwhile refactoring regardless, and will look into it, but this may take a bit of time. In the meantime, if this is a hard requirement, you can work around it by creating your own validator and applying it to the sequence (check out the section on custom combinators on the [http://wix.github.io/accord/dsl.html](Accord site) and let me know if you run into any trouble).

**Comment by alexanderweber** [comment]
Currently we decided to do the work around you referred to, by defining an implicit validator for sequences in general. It is still kind of a blocker criteria for using Accord in our case, so I am glad that we could expect a future improvement in that field. I am quiet satisfied with the rest of Accord's features, so it would be nice if you could let me know as soon as the feature is out there. I am eagerly waiting for it. Cheers

**Comment by holograph** [comment]
Initial work on overhauling the description generation framework can be found in the [description-overhaul](https://github.com/wix/accord/tree/description-overhaul) branch. There's still a ways to go in order to support mixing compile- and runtime-generated descriptions (e.g. property access vs specific array index) but it's slowly getting there. This should also support #58.
