### ISSUE TITLE
Adding a description to an expression with "as" doesn't label it

### ISSUE THREAD

**Issue by orium** [wix/accord#64]
For example this code

```scala
  val v = validator[Option[Int]] {
    _.each as "FOOOOO" must be == 0
  }

  println(v(Some(1)))
```

will print `Failure(Set(RuleViolation(1,got 1, expected 0,Some(value))))`.

**Comment by holograph** [comment]
This is a duplicate of #55, your input on the expected syntax/behaviour there would be greatly appreciated!
