### ISSUE TITLE
Resolving property names in explicit validators

### ISSUE THREAD

**Issue by zunder** [wix/accord#66]
I am having two validators defined in companion object of class `Bar(minValue: Double, maxValue: Double)`:

1. `defaultBarValidator` is implicit
2. `specialBarValidator` is not

There is also a class `Foo(bar: Bar)`. `Foo`'s validator explicitly calls the `specialBarValidator` validator on property by calling `foo.bar is specialBarValidator`. `specialBarValidator` looks like this:

```Scala
  lazy val specialBarValidator: Validator[Bar] = validator[Bar] { b =>
    b.minValue should be >= 0.5
    b.maxValue should be <= 1.0
  }
```

The validator works, but I am loosing the description information here. Instead of full path `bar.minValue`, I am only getting `bar`. Using implicit validator I am getting full description.

**Comment by holograph** [comment]
That shouldn't happen (implicit resolution has nothing to do with the description generation). Any chance you can post the full sample here?

**Comment by holograph** [comment]
Alright, managed to reproduce this with the following code:

```scala
package com.wix.accord.tests.repro

case class Bar(minValue: Double, maxValue: Double)
case object Bar {
  import com.wix.accord.Validator
  import com.wix.accord.dsl._

  implicit val defaultBarValidator: Validator[Bar] = validator[Bar] { b =>
    b.minValue should be >= 0.0
    b.maxValue should be <= 10.0
  }

  lazy val specialBarValidator: Validator[Bar] = validator[Bar] { b =>
    b.minValue should be >= 0.5
    b.maxValue should be <= 1.0
  }
}

case class Foo(bar: Bar)
case object Foo {
  import com.wix.accord.Validator
  import com.wix.accord.dsl._
  import Bar.specialBarValidator

  implicit val fooValidator: Validator[Foo] = validator[Foo] { f =>
    f.bar is specialBarValidator
  }
}

object Issue66 extends App {

  import com.wix.accord._
  println(
    validate(Foo(Bar(-0.4, 100.0)))
  )
}
```

**Comment by holograph** [comment]
Interesting conundrum: what should be the result?

* With the built-in delegation mechanism you would use `f.bar is valid(specialBarValidator)`; the resulting failure would include a `GroupViolation` that composes the specific rule failures, providing the complete information.
* `is` is intended for rules, which is why no `GroupViolation` is generated. Should the behavior in this case be identical to `valid`, or should the rendered description include the path information (e.g. `bar.minValue`)?

Comments would be appreciated...

**Comment by zunder** [comment]
Is there any advantage in _not_ generating a `GroupViolation` here? In our project we build a JSON output file, which is based on Failure structure. Having one consistent format would be easier to use here. But I think we covered all cases, so I would not mind either way.

**Comment by holograph** [comment]
This triggered yet another major refactoring of the description framework. The downside is a delay in releasing 0.6, the upside is that we'll have a proper spec for how descriptions are generated and combined...
