### ISSUE TITLE
Code examples do not compile

### ISSUE THREAD

**Issue by geirhe** [wix/accord#76]
See https://wix.github.io/accord/dsl.html and https://wix.github.io/accord/.

These seemingly place the implicit val ... validator code in the topmost level of a file. This is a scala syntax error.

E.g. defining a validator:

```
import dsl._    // Import the validator DSL

case class Person( firstName: String, lastName: String )
...

implicit val personValidator = validator[ Person ] { p =>
  p.firstName is notEmpty                   // The expression being validated is resolved automatically, see below
  p.lastName as "last name" is notEmpty     // You can also explicitly describe the expression being validated
}
...
```

The examples place the validators inside a case object. I suggest the documentation is updated to follow the examples.

**Comment by holograph** [comment]
While true, I'm not exactly sure this matters, this is a reduced example intended to give some idea of what it looks like. It works in the REPL, though perhaps some indication that the REPL is used might be appropriate...

**Comment by geirhe** [comment]
That would have saved me a couple of seconds, at least

**Comment by geirhe** [comment]
If you can show me where your docs are checked in, I can suggest a change?

**Comment by holograph** [comment]
Sure, we're using GitHub pages so it's on the [gh-pages](https://github.com/wix/accord/tree/gh-pages) branch. Be advised that significant changes are due with 0.6, hopefully in a few minutes.

**Comment by holograph** [comment]
This seems to me like fairly basic usage of Scala, but if you want to have a go at suggesting changes you're more than welcome.
