### ISSUE TITLE
Optional parameter

### ISSUE THREAD

**Issue by krishl7272** [wix/accord#85]
Hello there,

i am new to Scala and writing validations for Scala program..

Example:

case class ROOM (input: string,
                               output: string,
                               example: option [string] )

so i am defining like this..

case object ROOM {
import com.wix.accord.dsl
implicit val roomvalidator = validator [ROOM] { r=>
r. input is notEmpty
r.output is notEmpty
}
}
-------------------------
--->"example parameter" is "optional field" here and i want to "validate only if it is present in the user input"
--->"example parameter" has two field options 1.left
                                                                               2.right      and default option is "right"..

my question is ..

----> how to mention that "you should select one from left and right" ?

---> how to validate the "example parameter" only if it is present ...can you guys please help me out on this..

Thanks,

**Comment by holograph** [comment]
If I understand correctly, you want `example` to be valid if:

1. It is `None`
2. It is `Some("left")`
3. It is `Some("right")`

Is that correct? If so, you can use `r.example.each is in("left", "right")`.

**Comment by krishl7272** [comment]
exactly..
r.example.each is in("left", "right")
thanks ...its working for me
